// GENERATED by scripts/optimize-project-assets.mjs — do not edit.
//
// Every dimension here was reported by the image encoder, so templates can set
// intrinsic width/height and reserve the right box before the bytes arrive.
// Run `npm run assets:projects` to regenerate.

export interface GeneratedImage {
  /** Largest WebP variant — the `src` fallback. */
  readonly src: string;
  /** WebP candidates, or `null` for vector assets. */
  readonly srcset: string | null;
  /** AVIF candidates. Only generated for cover images. */
  readonly avif?: string | null;
  readonly width: number;
  readonly height: number;
}

export const PROJECT_MEDIA = {
  'nas-hr': {
    logo: {
      src: '/projects/nas-hr/logo.webp',
      srcset: null,
      width: 400,
      height: 110
    },
    shots: {
      dashboard: {
        src: '/projects/nas-hr/dashboard-1600.webp',
        srcset: '/projects/nas-hr/dashboard-800.webp 800w, /projects/nas-hr/dashboard-1600.webp 1600w',
        avif: '/projects/nas-hr/dashboard-800.avif 800w, /projects/nas-hr/dashboard-1600.avif 1600w',
        width: 1600,
        height: 737
      },
      employees: {
        src: '/projects/nas-hr/employees-1600.webp',
        srcset: '/projects/nas-hr/employees-800.webp 800w, /projects/nas-hr/employees-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 667
      },
      penalties: {
        src: '/projects/nas-hr/penalties-1600.webp',
        srcset: '/projects/nas-hr/penalties-800.webp 800w, /projects/nas-hr/penalties-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 636
      },
      'leave-requests': {
        src: '/projects/nas-hr/leave-requests-1600.webp',
        srcset: '/projects/nas-hr/leave-requests-800.webp 800w, /projects/nas-hr/leave-requests-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 712
      },
      attendance: {
        src: '/projects/nas-hr/attendance-1600.webp',
        srcset: '/projects/nas-hr/attendance-800.webp 800w, /projects/nas-hr/attendance-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 709
      }
    }
  },
  '2b': {
    logo: {
      src: '/projects/2b/logo.svg',
      srcset: null,
      width: 86,
      height: 51
    },
    shots: {
      home: {
        src: '/projects/2b/home-1600.webp',
        srcset: '/projects/2b/home-800.webp 800w, /projects/2b/home-1600.webp 1600w',
        avif: '/projects/2b/home-800.avif 800w, /projects/2b/home-1600.avif 1600w',
        width: 1600,
        height: 724
      },
      deals: {
        src: '/projects/2b/deals-1600.webp',
        srcset: '/projects/2b/deals-800.webp 800w, /projects/2b/deals-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 558
      },
      product: {
        src: '/projects/2b/product-1600.webp',
        srcset: '/projects/2b/product-800.webp 800w, /projects/2b/product-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 597
      },
      cart: {
        src: '/projects/2b/cart-510.webp',
        srcset: '/projects/2b/cart-510.webp 510w',
        avif: null,
        width: 510,
        height: 831
      },
      instalments: {
        src: '/projects/2b/instalments-602.webp',
        srcset: '/projects/2b/instalments-602.webp 602w',
        avif: null,
        width: 602,
        height: 874
      },
      checkout: {
        src: '/projects/2b/checkout-1600.webp',
        srcset: '/projects/2b/checkout-800.webp 800w, /projects/2b/checkout-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 613
      }
    }
  },
  nature: {
    logo: {
      src: '/projects/nature/logo.webp',
      srcset: null,
      width: 400,
      height: 256
    },
    shots: {
      home: {
        src: '/projects/nature/home-1600.webp',
        srcset: '/projects/nature/home-800.webp 800w, /projects/nature/home-1600.webp 1600w',
        avif: '/projects/nature/home-800.avif 800w, /projects/nature/home-1600.avif 1600w',
        width: 1600,
        height: 722
      },
      about: {
        src: '/projects/nature/about-1600.webp',
        srcset: '/projects/nature/about-800.webp 800w, /projects/nature/about-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 601
      },
      reach: {
        src: '/projects/nature/reach-1600.webp',
        srcset: '/projects/nature/reach-800.webp 800w, /projects/nature/reach-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 624
      },
      blog: {
        src: '/projects/nature/blog-1600.webp',
        srcset: '/projects/nature/blog-800.webp 800w, /projects/nature/blog-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 723
      },
      'admin-dashboard': {
        src: '/projects/nature/admin-dashboard-1600.webp',
        srcset: '/projects/nature/admin-dashboard-800.webp 800w, /projects/nature/admin-dashboard-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 730
      },
      'admin-services': {
        src: '/projects/nature/admin-services-1600.webp',
        srcset: '/projects/nature/admin-services-800.webp 800w, /projects/nature/admin-services-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 740
      },
      'admin-projects': {
        src: '/projects/nature/admin-projects-1600.webp',
        srcset: '/projects/nature/admin-projects-800.webp 800w, /projects/nature/admin-projects-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 763
      }
    }
  },
  esterad: {
    logo: {
      src: '/projects/esterad/logo.webp',
      srcset: null,
      width: 194,
      height: 48
    },
    shots: {
      home: {
        src: '/projects/esterad/home-1600.webp',
        srcset: '/projects/esterad/home-800.webp 800w, /projects/esterad/home-1600.webp 1600w',
        avif: '/projects/esterad/home-800.avif 800w, /projects/esterad/home-1600.avif 1600w',
        width: 1600,
        height: 709
      },
      listing: {
        src: '/projects/esterad/listing-1600.webp',
        srcset: '/projects/esterad/listing-800.webp 800w, /projects/esterad/listing-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 714
      },
      brands: {
        src: '/projects/esterad/brands-1600.webp',
        srcset: '/projects/esterad/brands-800.webp 800w, /projects/esterad/brands-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 719
      },
      categories: {
        src: '/projects/esterad/categories-1600.webp',
        srcset: '/projects/esterad/categories-800.webp 800w, /projects/esterad/categories-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 702
      },
      promotion: {
        src: '/projects/esterad/promotion-1600.webp',
        srcset: '/projects/esterad/promotion-800.webp 800w, /projects/esterad/promotion-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 586
      }
    }
  },
  'designed-by-g': {
    logo: {
      src: '/projects/designed-by-g/logo.webp',
      srcset: null,
      width: 400,
      height: 173
    },
    shots: {
      home: {
        src: '/projects/designed-by-g/home-1600.webp',
        srcset: '/projects/designed-by-g/home-800.webp 800w, /projects/designed-by-g/home-1600.webp 1600w',
        avif: '/projects/designed-by-g/home-800.avif 800w, /projects/designed-by-g/home-1600.avif 1600w',
        width: 1600,
        height: 725
      },
      collection: {
        src: '/projects/designed-by-g/collection-1600.webp',
        srcset: '/projects/designed-by-g/collection-800.webp 800w, /projects/designed-by-g/collection-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 579
      },
      editorial: {
        src: '/projects/designed-by-g/editorial-1600.webp',
        srcset: '/projects/designed-by-g/editorial-800.webp 800w, /projects/designed-by-g/editorial-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 605
      },
      product: {
        src: '/projects/designed-by-g/product-1102.webp',
        srcset: '/projects/designed-by-g/product-800.webp 800w, /projects/designed-by-g/product-1102.webp 1102w',
        avif: null,
        width: 1102,
        height: 798
      },
      'size-guide': {
        src: '/projects/designed-by-g/size-guide-1300.webp',
        srcset: '/projects/designed-by-g/size-guide-800.webp 800w, /projects/designed-by-g/size-guide-1300.webp 1300w',
        avif: null,
        width: 1300,
        height: 520
      },
      checkout: {
        src: '/projects/designed-by-g/checkout-1600.webp',
        srcset: '/projects/designed-by-g/checkout-800.webp 800w, /projects/designed-by-g/checkout-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 853
      }
    }
  },
  'nader-coffee': {
    logo: {
      src: '/projects/nader-coffee/logo.webp',
      srcset: null,
      width: 200,
      height: 200
    },
    shots: {
      home: {
        src: '/projects/nader-coffee/home-1600.webp',
        srcset: '/projects/nader-coffee/home-800.webp 800w, /projects/nader-coffee/home-1600.webp 1600w',
        avif: '/projects/nader-coffee/home-800.avif 800w, /projects/nader-coffee/home-1600.avif 1600w',
        width: 1600,
        height: 727
      },
      categories: {
        src: '/projects/nader-coffee/categories-1600.webp',
        srcset: '/projects/nader-coffee/categories-800.webp 800w, /projects/nader-coffee/categories-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 432
      },
      bestsellers: {
        src: '/projects/nader-coffee/bestsellers-1600.webp',
        srcset: '/projects/nader-coffee/bestsellers-800.webp 800w, /projects/nader-coffee/bestsellers-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 637
      },
      product: {
        src: '/projects/nader-coffee/product-1600.webp',
        srcset: '/projects/nader-coffee/product-800.webp 800w, /projects/nader-coffee/product-1600.webp 1600w',
        avif: null,
        width: 1600,
        height: 667
      },
      checkout: {
        src: '/projects/nader-coffee/checkout-1203.webp',
        srcset: '/projects/nader-coffee/checkout-800.webp 800w, /projects/nader-coffee/checkout-1203.webp 1203w',
        avif: null,
        width: 1203,
        height: 844
      }
    }
  }
} as const;
